on:
  push:
    branches:
      - main

jobs:
  update_pull_requests:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch list of open pull requests
      id: pr_list
      run: |
        PR_LIST=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls?state=open" | jq -r '.[] | .head.ref')
        echo "PR_LIST=$PR_LIST" >> $GITHUB_ENV
    
    - name: Fetch all branches and tags
      run: git fetch --prune --unshallow

    - name: Auto update pull requests
      run: |
        for pr_branch in $PR_LIST; do
          git checkout "$pr_branch"
          # if git rebase origin/main; then
          #   git push --force-with-lease
          # else
          #   # Conflict occurred, resolve by keeping our changes
          #   git checkout --ours .
          #   git add .
          #   git rebase --continue
          #   git push --force-with-lease
          # fi
        done